# Generated by Django 3.1.3 on 2020-11-30 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='users_account',
        ),
        migrations.AlterModelTable(
            name='history',
            table='users_history',
        ),
    ]
