# Generated by Django 3.1.3 on 2020-11-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201129_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='description',
            field=models.CharField(default='empty', max_length=256),
        ),
    ]
